#! /bin/bash

# commands
case "$1" in

core)

	cp ~/workspace/cc-phalcon/cc-phalcon.phar core/
	echo -e "Core updated"
;;

# default
*)
	TAG="latest"

	# build
	docker build -t npulidom/img-api:$TAG .
	echo -e "Build success"
;;
esac
