#! /bin/bash

# commands
case "$1" in

core)

	cp ~/workspace/cc-phalcon/cc-phalcon.phar core/
	echo -e "Core updated"
;;

push)

	TAG="${2:-latest}"

	docker push npulidom/img-api:$TAG
	echo -e "Build pushed"
;;

# default
*)
	TAG="${1:-latest}"
	OPTS="${2:-}"

	# build
	docker build $OPTS -t npulidom/img-api:$TAG .
	echo -e "Build success"
;;
esac
