#! /bin/bash
# author: Nicolas Pulido <nicolas.pulido@crazycake.cl>

# stop script if an error occurs
set -e

# set project path
PROJECT_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# app namespace
APP_NAME=${PWD##*/}

# help output
scriptHelp() {

	echo -e "\033[93m > "$APP_NAME" webapp CLI \033[0m"
	echo -e "\033[95m build: docker image build. Options: --push. \033[0m"
	echo -e "\033[95m php: runs app php CLI. \033[0m"
	echo -e "\033[95m clean: cleans cache & logs (storage folder).\033[0m"
	exit
}

# commands
case "$1" in


build)

	TAG="latest"

	# build
	docker build -t npulidom/img-api:$TAG .

	# push image
	if [ "$2" = "--push" ]; then
		docker push npulidom/img-api:$TAG
	fi
;;

php)

	echo -e "\033[95mRunning app php CLI... \033[0m"

	docker exec -it $APP_NAME bash -c "php /var/www/app/cli/cli.php main ${@:2}"
;;

clean)

	docker exec -it $APP_NAME bash -c 'find /var/www/storage/cache /var/www/storage/logs -type f \( ! -iname ".*" \) -print0 | xargs -0 rm -f'

	echo -e "\033[92mDone! \033[0m"
;;

#default
*)
	scriptHelp
;;
esac
